"""
modtranCards

Based on Michel's Makecard2A.py, modified to class structure & deal with single card at a time,
while removing hard-coded paths.

This class provides methods to translate atmospheric parameter inputs (generated by modtranSequences)
into the MODTRAN card templates, including the optional Card 2A (for cirrus clouds) and the
required card 2B to specify aerosol features. (from Michel) The template in use must specify
the 2 cards 2A+ which define the altitudes of the aerosol layers, essential to force ground-generated
altitudes at the altitude of the telescope. 

The class also provides a method to spawn a shell process to run MODTRAN (assuming you have the external
MODTRAN program and license). 

The file Cardtemplate.dat provides the base template for the MODTRAN card, as is kept in
${ATMOSPHERES_TRANSMISSION_DIR}/data. 

ljones@astro.washington.edu

"""

import os
from copy import deepcopy
import numpy


